### ISSUE TITLE
ListWindowShutter Value inverting did only invert the icon

### ISSUE THREAD

**Issue by Fiiti** [iobroker-community-adapters/ioBroker.vis-material-advanced#17]
Not pretty sure if it is a bug or feature request.

For Homematic Shutter you must invert the Value. Otherwise the Icon and the Control Slider are false shown. Open is shown as closed and vice versa.

But using the value invert Mark it only invert the icon, but not the slider. This seems to be unlogical in this manner.
 
So what do you think?
![2020-10-15 18_52_20-Window](https://user-images.githubusercontent.com/25975978/96161609-c8a73d80-0f17-11eb-8f37-384beae03c0f.png)

If the Shutter is quite open (e.g. 25%), the Slider should also be only at 25% - more to the left. Or?

 Regards Fi

**Comment by EdgarM73** [comment]
Hi Fiiti,

yes, this feature is for devices which show 100% as open and 0% as closed.

If I would change both the icon and the slider than only the view would be changed but not the behaviour.

Of course I could change the slider instead of the icon but this is also only for visibility and not functionality.

regards
E

**Comment by Fiiti** [comment]
Oh no. Both would be clever. Icon AND Slider.

Because both should be identical in behavior.
If the icon shows 25% closed (like the picture above), the slider should have only 25%.

Or just in case, another hook for the slider. 
So there are two inverted hooks: Icon and slider

**Comment by EdgarM73** [comment]
Hi Fiitii,

in the first version it was implemented as you described.

the problem is, if you change both, than you do not change anything, like in math:

x = y
-x = -y

is the same. I thought the same way as you until i tryed it.

what some need is
x = -y


I tried to change the slider setting to show the 100-value but was not successfull with jqueryui.slider.

regards
E
